# Generated by Django 5.2.11 on 2026-04-04 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikroraion',
            name='raion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mikroraiony', to='agency.raion', verbose_name='Район'),
        ),
    ]
