# Generated by Django 5.2.11 on 2026-04-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_alter_mikroraion_raion'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='fias_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='ФИАС ID региона'),
        ),
        migrations.AddField(
            model_name='region',
            name='kladr_id',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Код КЛАДР (первые 2 символа)'),
        ),
    ]
